### ISSUE TITLE
Erro na tela de visualização de matrículas devido a consulta em conclusão de etapas.  

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#266]
Ocorre um erro na tela visualização de matrículas de doutorado quando utilizado um banco de dados da Civil, semelhante ao erro abaixo: 

Erro:

NoMethodError (undefined method `duration' for nil:NilClass):
  
app/models/phase.rb:36:in `total_duration'
app/models/phase_completion.rb:40:in `calculate_due_date'
app/models/phase_completion.rb:33:in `init'

O erro acontece durante a busca dos dados que alimentam a caixa de conclusão de etapas presente na tela de visualização.

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
Antes de exibir as datas de validade das conclusões de etapa na tela de visualização de matrícula, a tela tenta atualizar a validade (due_date) de cada etapa com base na duração dessas etapas. Se a etapa não tiver duração definida, o valor da validade não é atualizado, e o valor já existente é exibido. Porém se a etapa tiver uma duração definida para nível qualquer (mesmo não sendo o mesmo da matrícula), ele tenta recalcular a validade, o que causa o erro se o nível não estiver definido para o mesmo nível da matrícula.

Foi acrescentada uma verificação de nível para evitar que ele tente recalcular a validade caso essa não esteja definida.
