### ISSUE TITLE
Corrigir teste de spec do modelo ResearchArea

### ISSUE THREAD

**Issue by Carlos-Eduardo-Cabral-da-Cunha** [gems-uff/sapos#270]
Ocorrem erros durante o teste de spec quando executado o comando:
rspec spec/models/research_area_spec.rb
Com a seguinte falha:

  1) ResearchArea should restrict destroy when exists :course
     Failure/Error: FactoryGirl.create(dependent_class, @fk=> obj.id)
     
     NoMethodError:
       undefined method research_area_id=' for #<Course:0xb98f9bc>
       Did you mean?  research_area_ids=
                      research_area_ids
                      research_area=
                      research_area
                      research_areas=
                      research_areas
      #./spec/support/matchers/dependent_matchers.rb:44:in 'block (2 levels) in <top (required)>'
      #./spec/models/research_area_spec.rb:8:in `block (2 levels) in <top (required)>'

**Comment by Carlos-Eduardo-Cabral-da-Cunha** [comment]
O teste considerava um caso anterior onde uma disciplina estaria associada a
apenas uma área de pesquisa. Como agora uma disciplina pode ter mais de uma
área de pesquisa, o teste foi modificado para atender a mudança.
